config_version: 1

# General settings.
general:
  # The CyanogenMod codename of the device.
  cm_device_codename:
  # Preferred CyanogenMod release type
  cm_release_type: snapshot
  # Preferred CyanogenMod release version
  cm_release_version: M12
  template: mia-default

defaults:
  # The default repository for apps.
  repository_id: fdroid

app_types:
  system: system/app
  privileged: system/priv-app
  user: data/app

# A list of repositories for the F-Droid application.
repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

# Apps from the main F-Droid repository.
apps:
  - id: org.fdroid.fdroid
    versioncode: 830
    app_type: privileged
  - id: info.guardianproject.orfox
    url: https://guardianproject.info/builds/OrfoxFennec/2014-08-22_23-32-22/OrfoxFennec-debug.apk
  - id: org.anhonesteffort.flock
    url: https://flock-supplychain.s3.amazonaws.com/apks/org.anhonesteffort.flock-4b93f078-cae6-4997-a1c2-ef833b2ac2c1.apk
  - id: com.artifex.mupdfdemo
  - id: com.csipsimple
  - id: com.fsck.k9
  - id: com.morlunk.mumbleclient
  - id: com.projectsexception.myapplist.open
  - id: com.xabber.androiddev
  - id: de.schildbach.wallet
  - id: fr.kwiatkowski.ApkTrack
  - id: indrora.atomic
  - id: net.osmand.plus
  - id: org.coolreader
  - id: org.ethack.orwall
  - id: org.mariotaku.twidere
  - id: org.mozilla.fennec_fdroid
  - id: org.sufficientlysecure.keychain
  - id: org.nick.cryptfs.passwdmanager
  - id: org.sufficientlysecure.localcalendar
  - id: org.torproject.android
  - id: org.videolan.vlc
  - id: be.uhasselt.privacypolice
