
# General settings.
general:
  # The CyanogenMod codename of the device.
  cm_device_codename:
  # Preferred CyanogenMod release type
  cm_release_type: snapshot
  # Preferred CyanogenMod release version
  cm_release_version: M12
  template: mia-default

defaults:
  # The default repository for apps.
  repository_id: fdroid

# Mapping of the items in the definition and their place in the update archive.
update_content:
  - src: init.d
    dst: system/etc/init.d
  - src: META-INF
    dst: META-INF
  - src: misc
    dst: sdcard/misc
  - src: system-apps
    dst: system/priv-app
  - src: system-lib
    dst: system/lib
  - src: user-apps
    dst: data/app
  - src: user-data
    dst: data/data
  - src: other/update-binary
    dst: META-INF/com/google/android/update-binary
  - src: other/updater-script
    dst: META-INF/com/google/android/updater-script
  - src: other/firstboot.sh
    dst: data/.firstboot.sh

# A list of repositories for the F-Droid application.
repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

# Apps from the main F-Droid repository.
apps:
  - name: org.fdroid.fdroid
    code: 830
    path: system-apps
  - name: info.guardianproject.orfox
    url: https://guardianproject.info/builds/OrfoxFennec/2014-08-22_23-32-22/OrfoxFennec-debug.apk
  - name: org.anhonesteffort.flock
    url: https://flock-supplychain.s3.amazonaws.com/apks/org.anhonesteffort.flock-4b93f078-cae6-4997-a1c2-ef833b2ac2c1.apk
  - name: com.artifex.mupdfdemo
  - name: com.csipsimple
  - name: com.fsck.k9
  - name: com.morlunk.mumbleclient
  - name: com.projectsexception.myapplist.open
  - name: com.xabber.androiddev
  - name: de.schildbach.wallet
  - name: fr.kwiatkowski.ApkTrack
  - name: indrora.atomic
  - name: net.osmand.plus
  - name: org.coolreader
  - name: org.ethack.orwall
  - name: org.mariotaku.twidere
  - name: org.mozilla.fennec_fdroid
  - name: org.sufficientlysecure.keychain
  - name: org.nick.cryptfs.passwdmanager
  - name: org.sufficientlysecure.localcalendar
  - name: org.torproject.android
  - name: org.videolan.vlc
