config_version: 1

# General settings.
general:
  # The codename of the device.
  device_codename:
  # The operating system name.
  os_name: cm
  # The operating system version.
  os_version: 11
  # The template name.
  template: mia-default

defaults:
  # The default repository for apps.
  repository: fdroid

app_types:
  system: system/app
  privileged: system/priv-app
  user: data/app

# A list of repositories for the F-Droid application.
repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive
    # Until full release in official F-Droid repo
  - id: guardian_orfox
    name: Orfox Development
    url: https://dev.guardianproject.info/debug/info.guardianproject.orfox/fdroid/repo

# Apps from the main F-Droid repository.
apps:
  - id: org.fdroid.fdroid
    versioncode: 95150
    hash: 2003977ec3b19fd2a5caa46ddd546294e5ee7b096fc8bd0261e94ded1e2f719f
    app_type: privileged
  - id: info.guardianproject.orfox
    repository: guardian_orfox
  - id: com.artifex.mupdfdemo
  - id: com.csipsimple
  - id: com.fsck.k9
  - id: com.morlunk.mumbleclient
  - id: com.projectsexception.myapplist.open
  - id: com.xabber.androiddev
  - id: de.schildbach.wallet
  - id: fr.kwiatkowski.ApkTrack
  - id: indrora.atomic
  - id: net.osmand.plus
  - id: org.coolreader
  - id: org.ethack.orwall
  - id: org.mariotaku.twidere
  - id: org.mozilla.fennec_fdroid
  - id: org.sufficientlysecure.keychain
  - id: org.nick.cryptfs.passwdmanager
  - id: org.sufficientlysecure.localcalendar
  - id: org.torproject.android
    versioncode: 133
  - id: org.videolan.vlc
  - id: be.uhasselt.privacypolice
