config_version: 2-beta

general:
  device_codename: grouper
  os_version: 12.1
  template: mia-default

defaults:
  repository: fdroid
  app_type: user

app_types:
  system: system/app
  privileged: system/priv-app
  user: data/app

repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

apps:
  - id: org.fdroid.fdroid
    versioncode: 95150
    hash: 2003977ec3b19fd2a5caa46ddd546294e5ee7b096fc8bd0261e94ded1e2f719f
    app_type: privileged
  - id: info.guardianproject.orfox
    url: https://guardianproject.info/builds/OrfoxFennec/latest/OrfoxFennec-debug.apk
  - id: com.artifex.mupdfdemo
    version: 1.2.3
  - org.torproject.android
  - org.videolan.vlc
