config_version: 2-beta

general:
  cm_device_codename: grouper
  cm_release_type: snapshot
  cm_release_version: M12
  template: mia-default

defaults:
  repository: fdroid

app_types:
  system: system/app
  privileged: system/priv-app
  user: data/app

repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

apps:
- id: org.fdroid.fdroid
  versioncode: 830
  app_type: system
- id: info.guardianproject.orfox
  url: https://guardianproject.info/builds/OrfoxFennec/latest/OrfoxFennec-debug.apk
- id: com.artifex.mupdfdemo
  version: 1.2.3
- org.torproject.android
- org.videolan.vlc
