config_version: map(int(), str())

general:
  cm_device_codename: str(required=False)
  cm_release_type: str()
  cm_release_version: str()
  template: str(required=False)

repositories: list(include('repository'))

apps: >
  list(
    str(),
    include('app_fdroid_latest'),
    include('app_fdroid_version'),
    include('app_fdroid_versioncode'),
    include('app_direct_download'),
  )

defaults:
  repository_id: str()
  app_type: str(required=False)

---

repository:
  id: str()
  name: str()
  url: str()
  fallback: str(required=False)

app_fdroid_latest:
  id: str()
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)

app_fdroid_version:
  id: str()
  version: str()
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)

app_fdroid_versioncode:
  id: str()
  versioncode: int()
  repository: str(required=False)
  app_type: enum('system', 'privileged', 'user', required=False)

app_direct_download:
  id: str()
  name: str()
  url: str()
  app_type: enum('system', 'privileged', 'user', required=False)
