config_version: map(int(), str())

general:
  cm_device_codename: str()
  cm_release_type: str()
  cm_release_version: str()
  template: str(required=False)

repositories: list(include('repository'))

apps: list(include('app_fdroid_simple'), include('app_fdroid_version'), include('app_fdroid_versioncode'), include('app_direct_download'))

defaults:
  repository: str()
  install_type: str()

---

repository:
  id: str()
  name: str()
  url: str()
  fallback: str(required=False)

app_fdroid_simple: str()

app_fdroid_version:
  id: str()
  version: str(required=False)
  repository: str(required=False)
  install_type: enum('system', 'privileged', 'user', required=False)

app_fdroid_versioncode:
  id: str()
  versioncode: int(required=False)
  repository: str(required=False)
  install_type: enum('system', 'privileged', 'user', required=False)

app_direct_download:
  id: str()
  url: str()
  install_type: enum('system', 'privileged', 'user', required=False)
