config_version: 2

general:
  cm_device_codename: grouper
  cm_release_type: snapshot
  cm_release_version: M12
  parent_template: mia-default

repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

install_types:
  - id: system
    path: system/app
  - id: privileged
    path: system/priv-app
  - id: user
    path: data/app

defaults:
  repository_id: fdroid
  install_type: user

apps:
- id: org.fdroid.fdroid
  versioncode: 830
  install_type: system
- id: info.guardianproject.orfox
  name: Orfox
  url: https://guardianproject.info/builds/OrfoxFennec/latest/OrfoxFennec-debug.apk
- id: com.artifex.mupdfdemo
  version: "1.2.3"
- id: com.csipsimple
- id: com.fsck.k9
- com.morlunk.mumbleclient
- com.projectsexception.myapplist.open
- com.xabber.androiddev
- de.schildbach.wallet
- fr.kwiatkowski.ApkTrack
- indrora.atomic
- net.osmand.plus
- org.coolreader
- org.ethack.orwall
- org.mariotaku.twidere
- org.mozilla.fennec_fdroid
- org.sufficientlysecure.keychain
- org.nick.cryptfs.passwdmanager
- org.sufficientlysecure.localcalendar
- org.torproject.android
- org.videolan.vlc
