config_version: 2

general:
  cm_device_codename: grouper
  cm_release_type: snapshot
  cm_release_version: M12
  parent_templates:
    - mia-default
    - wifi-only

defaults:
  repository: fdroid
  app_type: user
  hash_type: sha256

app_types:
  system: system/app
  privileged: system/priv-app
  user: data/app

repositories:
  - id: fdroid
    name: F-Droid
    url: https://f-droid.org/repo
    fallback: fdroid_archive
  - id: fdroid_archive
    name: F-Droid Archive
    url: https://f-droid.org/archive

apps:
  - id: org.fdroid.fdroid
    versioncode: 920
    hash: 0e949b83d48d882ce70e1e405d25173f572b32623a8a8f58394193d3eac08f31
    app_type: system
  - id: info.guardianproject.orfox
    name: Orfox
    url: https://guardianproject.info/builds/OrfoxFennec/latest/OrfoxFennec-debug.apk
    hash: be85ee0f127d852b052715290e7e29ff
    hash_type: md5
  - id: com.artifex.mupdfdemo
    version: 1.2.3
  - org.torproject.android
  - org.videolan.vlc
